### ISSUE TITLE
Notice some Undefined Index and Variable

### ISSUE THREAD

**Issue by dragonjon** [nlybe/Elgg-News#3]
Hi @nlybe all is working perfect but some Notice in server log in my dev site testing your plugin 2.3.10

NOTICE: PHP (errno 8): 2017-10-07 15:06:15 (CEST): "Undefined index: page" in file /public_html/mod/amapnews/views/default/resources/amapnews/all.php (line 39)
NOTICE: PHP (errno 8): 2017-10-07 15:06:15 (CEST): "Undefined variable: selected_category" in file /public_html/mod/amapnews/views/default/resources/amapnews/all.php (line 39)
NOTICE: PHP (errno 8): 2017-10-07 15:06:15 (CEST): "Undefined index: page" in file /public_html/mod/amapnews/views/default/resources/amapnews/all.php (line 40)

Good work
Thanks
Jon

**Comment by dragonjon** [comment]
Hi @nlybe another deprecated messages:

WARNING: Deprecated in 2.3: elgg_view_input() is deprecated. Use elgg_view_field() Called from [#20] /public_html/vendor/elgg/elgg/engine/lib/views.php:1387<br /> -> [#19] /public_html/mod/amapnews/views/default/plugins/amapnews/settings.php:25

WARNING: Deprecated in 2.3: elgg_view_input() is deprecated. Use elgg_view_field() Called from [#16] /public_html/vendor/elgg/elgg/engine/lib/views.php:1387<br /> -> [#15] /public_html/mod/amapnews/views/default/forms/amapnews/add.php:70. 78, 86,103, 113, 121

Good work
Thanks
Jon

**Comment by nlybe** [comment]
The "Undefined index: page" fixed with minor version 2.3.12.1

The deprecated messages fixed on v3.13
