### ISSUE TITLE
When plugin is activated it disables user commenting in Discussions

### ISSUE THREAD

**Issue by Danie10** [nlybe/Elgg-News#4]
Had users complain they could not leave comments in discussions (only admins could comment). Disabled all plugins and comments worked. Enabled and tested after each one and found the News plugin causing the issue. I tried also deselecting all its settings for the plugin, but it still affected commenting. Moment I deactivate the plugin, all comments are working again.

Have v3.14 of plugin installed an Elgg v3.3.6. No updates pending and caches were all flushed.

**Comment by nlybe** [comment]
Hi there. I reproduced this issue, so I am going to fix it.
